Feature/migl/rdphoen 618 fw version
iris-GmbH/meta-iris-base pull request #117
Opened 2022-07-11 06:41 UTC by linkjumper

2022-07-18 14:26 UTC, sven-foerster approved these changes

2022-07-19 08:15 UTC, Jasper-Ben requested changes

2022-07-19 08:15 UTC, Jasper-Ben commented on recipes-support/swupdate/swupdate/swupdate_default_args
> +FW_VERSION=`grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' /etc/version`
Please do not use /etc/version. This is currently only kept for backwards compatibility and should be deprecated at some point. Use /etc/os-release instead.

2022-07-19 20:13 UTC, Jasper-Ben approved these changes

2022-07-19 20:14 UTC, merged