Feature/phsc/rdphoen 1257 lvm resize
iris-GmbH/meta-iris-base pull request #132
Opened 2022-07-28 15:50 UTC by irisPHSC

## Test increase logical volume size
mount over config to configure lvm
`mkdir -p /tmp/etc/lvm; mount --bind /tmp/etc/lvm /etc/lvm`
see which firmware is booted
`lsblk`
resize firmware lv that is not booted
`lvresize --force --yes --quiet -L 50MB /dev/mapper/irma6lvm-rootfs_b`
trigger swupdate
```
[read_lines_notify] : Resize rootfs logical volume: 54525952 -> 75942912
[read_lines_notify] : Rounding size to boundary between physical extents: 76.00 MiB.
[read_lines_notify] : Size of logical volume irma6lvm/rootfs_b changed from 52.00 MiB (13 extents) to 76.00 MiB (19 extents).
[read_lines_notify] : Logical volume irma6lvm/rootfs_b successfully resized.
```
## Test decrease logical volume size
mount over config to configure lvm
`mkdir -p /tmp/etc/lvm; mount --bind /tmp/etc/lvm /etc/lvm`
see which firmware is booted
`lsblk`
resize firmware lv that is not booted
`lvresize --force --yes --quiet -L 100MB /dev/mapper/irma6lvm-rootfs_a`
trigger swupdate
```
[read_lines_notify] : Resize rootfs logical volume: 104857600 -> 75942912
[read_lines_notify] : Rounding size to boundary between physical extents: 76.00 MiB.
[read_lines_notify] : Size of logical volume irma6lvm/rootfs_b changed from 100.00 MiB (25 extents) to 76.00 MiB (19 extents).
[read_lines_notify] : Logical volume irma6lvm/rootfs_b successfully resized.
```
## Test same logical volume size

just trigger swupdate without any modifications. No lv resizing should take place.
```
[read_lines_notify] : Resize rootfs logical volume: 79691776 -> 75942912
[read_lines_notify] : Rounding size to boundary between physical extents: 76.00 MiB.
```

2022-07-28 19:23 UTC, linkjumper requested changes
Resizing works!

```
# maintenance -> dev
[INFO ] : SWUPDATE running :  Installation in progress
[TRACE] : SWUPDATE running :  [read_lines_notify] : Resize rootfs logical volume: 79691776 -> 302155776
[TRACE] : SWUPDATE running :  [read_lines_notify] :   Rounding size to boundary between physical extents: 292.00 MiB.
[TRACE] : SWUPDATE running :  [read_lines_notify] :   Size of logical volume irma6lvm/rootfs_a changed from 76.00 MiB (19 extents) to 292.00 MiB (73 extents).
[TRACE] : SWUPDATE running :  [read_lines_notify] :   Logical volume irma6lvm/rootfs_a successfully resized.
[TRACE] : SWUPDATE running :  [read_lines_notify] : 180274504
[TRACE] : SWUPDATE running :  [run_system_cmd] : /tmp/scripts/pre_post_inst.sh preinst  command returned 0

# dev -> maintenance
[INFO ] : SWUPDATE running :  Installation in progress
[TRACE] : SWUPDATE running :  [read_lines_notify] : Resize rootfs logical volume: 306184192 -> 76081152
[TRACE] : SWUPDATE running :  [read_lines_notify] :   Rounding size to boundary between physical extents: 76.00 MiB.
[TRACE] : SWUPDATE running :  [read_lines_notify] :   Size of logical volume irma6lvm/rootfs_a changed from 292.00 MiB (73 extents) to 76.00 MiB (19 extents).
[TRACE] : SWUPDATE running :  [read_lines_notify] :   Logical volume irma6lvm/rootfs_a successfully resized.
[TRACE] : SWUPDATE running :  [read_lines_notify] : 180274504
[TRACE] : SWUPDATE running :  [run_system_cmd] : /tmp/scripts/pre_post_inst.sh preinst  command returned 0

# maintenance -> maintenance
[INFO ] : SWUPDATE running :  Installation in progress
[TRACE] : SWUPDATE running :  [read_lines_notify] : Resize rootfs logical volume: 79691776 -> 76081152
[TRACE] : SWUPDATE running :  [read_lines_notify] :   Rounding size to boundary between physical extents: 76.00 MiB.
[TRACE] : SWUPDATE running :  [read_lines_notify] : 180274504
[TRACE] : SWUPDATE running :  [run_system_cmd] : /tmp/scripts/pre_post_inst.sh preinst  command returned 0
```

2022-07-28 19:23 UTC, linkjumper commented on recipes-support/irma6-swuimage/files/pre_post_inst.sh
> +	if [ $new_size -ne $cur_size ]; then
It seems this case is always entered because the new size is always rounded up.
```
#maintenance -> maintenance
[INFO ] : SWUPDATE running :  Installation in progress
[TRACE] : SWUPDATE running :  [read_lines_notify] : Resize rootfs logical volume: 79691776 -> 76081152
[TRACE] : SWUPDATE running :  [read_lines_notify] :   Rounding size to boundary between physical extents: 76.00 MiB.
[TRACE] : SWUPDATE running :  [read_lines_notify] : 180274504
[TRACE] : SWUPDATE running :  [run_system_cmd] : /tmp/scripts/pre_post_inst.sh preinst  command returned 0
```

2022-07-28 19:23 UTC, linkjumper commented on recipes-support/irma6-swuimage/files/pre_post_inst.sh
> +	new_size=$(openssl enc -d -aes-256-cbc -K "$key" -iv "$iv" -in "$rootfs_file" | zcat | wc -c)
**[No change needed here]**
I have tested Ian suggestion to add an entry in the sw-description like. You could also grep for `decrypted_size` on `/tmp/sw-description` in this script. Just in case time is a problem.
```
        {
            filename = "irma6-maintenance-imx8mp-irma6r2.ext4.gz";
            type = "raw";
            device = "/dev/swu_rootfs";
            version = "irma6-maintenance-2.0.6-dev-20220728155525";
            compressed = "zlib";
            sha256 = "980fd8e04cd2f903cf6af42b5832cb6be586ffb9fa8bc3033377fdca75079b1e";
            ivt = "b45363d2ce512d57c31ae0d0aaa67876";
            encrypted = true;
            decrypted_size = "76081152";
        },
```

2022-07-28 20:17 UTC, sven-foerster commented
$ mkdir -p /tmp/etc/lvm; mount --bind /tmp/etc/lvm /etc/lvm

$ lsblk
NAME                              MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINT
mmcblk2                           179:0    0  3.7G  0 disk  
|-mmcblk2p1                       179:1    0    7M  0 part  
|-mmcblk2p2                       179:2    0  128M  0 part  
|-mmcblk2p3                       179:3    0  128M  0 part  
|-mmcblk2p4                       179:4    0  128M  0 part  
`-mmcblk2p5                       179:5    0  3.3G  0 part  
  |-irma6lvm-rootfs_a             252:0    0   76M  0 lvm   
  | `-decrypted-irma6lvm-rootfs_a 252:8    0   76M  0 dm    
  |   `-verity-rootfs_a           252:10   0 72.6M  1 crypt /
  |-irma6lvm-rootfs_a_hash        252:1    0    4M  0 lvm   
  | `-verity-rootfs_a             252:10   0 72.6M  1 crypt /
  |-irma6lvm-rootfs_b             252:2    0   76M  0 lvm   
  |-irma6lvm-rootfs_b_hash        252:3    0    4M  0 lvm   
  |-irma6lvm-userdata             252:4    0  512M  0 lvm   
  | `-decrypted-irma6lvm-userdata 252:9    0  512M  0 dm    /mnt/iris
  |-irma6lvm-staticdata           252:5    0  128M  0 lvm   
  |-irma6lvm-staticdata_hash      252:6    0    8M  0 lvm   
  `-irma6lvm-keystore             252:7    0  128M  0 lvm   
mmcblk2boot0                      179:32   0    4M  1 disk  
mmcblk2boot1                      179:64   0    4M  1 disk  

$ lvresize --force --yes --quiet -L 50MB /dev/mapper/irma6lvm-rootfs_b
  Rounding size to boundary between physical extents: 52.00 MiB.
  WARNING: Reducing active logical volume to 52.00 MiB.
  THIS MAY DESTROY YOUR DATA (filesystem etc.)
  Size of logical volume irma6lvm/rootfs_b changed from 76.00 MiB (19 extents) to 52.00 MiB (13 extents).
  Logical volume irma6lvm/rootfs_b successfully resized.

**But "Upload Firmware-Update" does not work:**
![grafik](https://user-images.githubusercontent.com/106246758/181628786-856a9409-5d5c-4b4a-afc0-ea3d91432dbf.png)

2022-07-29 07:31 UTC, Eximmius approved these changes
Could not update from the latest fw, prob. breaking changes. LVM Resizing ist working!

2022-07-29 09:34 UTC, sven-foerster approved these changes

2022-07-29 11:00 UTC, linkjumper requested changes

2022-07-29 11:00 UTC, linkjumper commented on recipes-support/irma6-swuimage/files/pre_post_inst.sh
> +	if [ $new_size -ne $cur_size ]; then
Please stop update here if new_size or cur_size is empty

2022-07-29 12:21 UTC, Jasper-Ben requested changes

2022-07-29 12:21 UTC, Jasper-Ben commented on recipes-support/irma6-swuimage/files/pre_post_inst.sh
> +	if [ ! -e /tmp/*.ext4.gz ]; then
if [ ! -e /tmp/*.ext4.gz ]; then
                  ^------------^ SC2144 (error): -e doesn't work with globs. Use a for loop.

2022-07-29 12:23 UTC, linkjumper approved these changes

2022-08-01 08:46 UTC, irisPHSC commented on recipes-support/irma6-swuimage/files/pre_post_inst.sh
> +	if [ ! -e /tmp/*.ext4.gz ]; then
Removed globbing and use filename from sw-description file

2022-08-01 11:59 UTC, Jasper-Ben approved these changes

2022-08-01 11:59 UTC, merged