[RDPHOEN-1228] swupdate check SRK
iris-GmbH/meta-iris-base pull request #135
Opened 2022-08-04 13:20 UTC by Eximmius

#### Avoids an update if the bootloader SRKs do not match the current SRKs burned in the fuses.
Firmware: (waiting for gitlab fix)
to do: include SRK revocation: [RDPHOEN-1278](https://jira.iris-sensing.net/browse/RDPHOEN-1278)

Test 1 - Without secure boot active, SRKs are not checked:
```
Secure boot is not activated, skipping SRK fuses verification
```
Test 2 - Board with secure boot active and mathing uboot:
```
SRK Bootloader verification passed
```
Test 3 - Board with secure boot active and not matching uboot:
```
Aborting, SRK Bootloader does not match SRK Fuse!
SRK Bootloader: 0x3b8ad329
...
SRK Fuse: 0x96ed4c5c
...
```

2022-08-09 00:40 UTC, Jasper-Ben approved these changes

2022-08-15 12:45 UTC, linkjumper requested changes

2022-08-15 12:45 UTC, linkjumper commented on recipes-support/cst/hab-csf-parser_3.3.1.bb
> +LICENSE = "CLOSED"
Does the license match? Same for hab.srktool-scripts

2022-08-15 12:45 UTC, linkjumper commented on recipes-support/cst/hab-csf-parser_3.3.1.bb
> +
`FILES_${PN} += "${bindir}/csf_parser"` is missing

2022-08-15 12:45 UTC, linkjumper commented on recipes-support/cst/hab-srktool-scripts_3.3.1.bb
> +
`FILES_${PN} += " \
    ${bindir}/createSRKFuses \
    ${bindir}/createSRKTable \
"` is missing!

2022-08-15 12:45 UTC, linkjumper commented on recipes-support/cst/files/0001-createSRKFuses-add-ecc-keys.patch
> +From: Ian Dannapel <ian.dannapel@iris-sensing.com>
Could you fix this patch mainline later? We probably need a ticket for that.

2022-08-15 12:45 UTC, linkjumper commented on recipes-support/irma6-swuimage/files/pre_post_inst.sh
> +	flashbin_file="/tmp/$flashbin_file"
First: That's not a blocking issue!

I am ok with fixed name: `/tmp/imx-boot.signed`. Even better ld be to replace variables in the pre_post_inst.sh at buildtime like we often do in other cases.

By that I mean:
- Renaming pre_post_inst.sh to pre_post_inst.sh.in
- Coping pre_post_inst.sh.in to pre_post_inst.sh
- Inplace rename variables with sed

Like using `/tmp/@@SWU_BOOTLOADER@@`

2022-08-15 13:57 UTC, Eximmius commented on recipes-support/cst/hab-csf-parser_3.3.1.bb
> +LICENSE = "CLOSED"
This is the same from https://source.denx.de/denx/meta-secure-imx/-/blob/dunfell/recipes-support/cst/cst-native.inc

2022-08-16 09:56 UTC, linkjumper requested changes

2022-08-16 09:57 UTC, linkjumper requested changes

2022-08-16 09:57 UTC, linkjumper commented on recipes-support/irma6-swuimage/files/pre_post_inst.sh
> +        count=${2} 			# count = number of words to be read
Use tabs to be consistent with the rest

2022-08-16 13:54 UTC, Eximmius commented on recipes-support/irma6-swuimage/files/pre_post_inst.sh
> +	(cd /tmp/ && csf_parser -s "$flashbin_file_decrypted" > /dev/null 2>&1)
csf_parser can only extract one SRK from an image. Since the flash.bin has the SRKs attached two times, the second one fails.

2022-08-16 14:20 UTC, Eximmius commented on recipes-support/irma6-swuimage/files/pre_post_inst.sh
> +	srk_fuses=$(imx_fuse_read 24 $srk_count)
Very odd indeed. I do not know why this happens, but the SRK hashes from the fuses are read correctly:
```
# dd if=/sys/bus/nvmem/devices/imx-ocotp0/nvmem bs=4 count=8 skip=24 | hexdump -e '"0x%04x\n"'                                                             
dd: /sys/bus/nvmem/devices/imx-ocotp0/nvmem: cannot skip to specified offset
8+0 records in
8+0 records out
32 bytes copied, 0.0002025 s, 158 kB/s
0x96ed4c5c
0xf412cfcd
0x44132cb3
0x17bbd035
0xa4cc2a59
0xcfd166d3
0xd3f0af3
0xdbcc1d9c

# hexdump -e '"%08_ax: " 4/4 "%08x " "\n"' /sys/bus/nvmem/devices/imx-ocotp0/nvmem
00000000: ffafa9eb 0002aaff 4198d5b9 1a260800
00000010: 20024591 01000018 0000007f 88000000
00000020: 00000000 00000000 00000000 00000000
*
00000040: badabada badabada badabada badabada
*
00000060: 96ed4c5c f412cfcd 44132cb3 17bbd035
00000070: a4cc2a59 cfd166d3 0d3f0af3 dbcc1d9c
```

2022-08-16 14:25 UTC, Eximmius commented on recipes-support/irma6-swuimage/files/pre_post_inst.sh
> +	flashbin_file=$(cat sw-description | tr '\n' ' ' | grep -o '{[^}]*device = "/dev/swu_bootloader"[^}]*}' | grep -o 'filename = "[^"]*";' | cut -d'"' -f 2)
Oops :smiling_face_with_tear: will fix it!

2022-08-16 14:25 UTC, Eximmius commented on recipes-support/irma6-swuimage/files/pre_post_inst.sh
> +	rootfs_file=$(cat sw-description | tr '\n' ' ' | grep -o '{[^}]*device = "/dev/swu_rootfs"[^}]*}' | grep -o 'filename = "[^"]*";' | cut -d'"' -f 2)
fixing!

2022-08-16 18:26 UTC, linkjumper commented on recipes-support/irma6-swuimage/files/pre_post_inst.sh
> +	srk_fuses=$(imx_fuse_read 24 $srk_count)
https://github.com/coreutils/coreutils/blob/master/src/dd.c#L2136

The warning `dd: /sys/bus/nvmem/devices/imx-ocotp0/nvmem: cannot skip to specified offset` does not occur if one have a temporary copy of the fuses. So I guess it is ok to ignore it.

```
cat /sys/bus/nvmem/devices/imx-ocotp0/nvmem > blub
dd if=blub bs=4 count=8 skip=24                                                                                                                                   
8+0 records in                                                                                                                                                                                 
8+0 records out                                                                                                                                                                                
32 bytes copied, 0.0015425 s, 20.7 kB/s
```

2022-08-17 08:43 UTC, Eximmius commented
New Gitlab: https://gitlab.devops.defra01.iris-sensing.net/MIRROR/iris-kas/-/pipelines/1691

2022-08-17 12:30 UTC, linkjumper approved these changes
Since I don't have a locked board, I was only able to do a dry run. Code is ok! For a real test, please have @irisPHSC  or @iris-ersc confirm it again.

2022-08-18 10:31 UTC, irisPHSC approved these changes
Firmware with matching SRKs :heavy_check_mark:
Firmware with different SRKs :heavy_check_mark:
```
2018-03-11T07:13:55.265340+00:00 i6-00-24-ea-03-9f-f7 swupdate: RUN Installation in progress
2018-03-11T07:13:55.288344+00:00 i6-00-24-ea-03-9f-f7 /tmp/scripts/pre_post_inst.sh: Update firmware_b
2018-03-11T07:13:55.726281+00:00 i6-00-24-ea-03-9f-f7 /tmp/scripts/pre_post_inst.sh: Aborting, SRK Bootloader does not match SRK Fuse!
2018-03-11T07:13:55.729031+00:00 i6-00-24-ea-03-9f-f7 /tmp/scripts/pre_post_inst.sh: SRK Bootloader: 0x5a29baa2#0120x9d2738f8#0120x85b059f8#0120x8c712a1e#0120x2e90eb4c#0120xea64c14c#0120x19b37113#0120x19198221
2018-03-11T07:13:55.731763+00:00 i6-00-24-ea-03-9f-f7 /tmp/scripts/pre_post_inst.sh: SRK Fuse: 0x3b8ad329#0120xe5e9be2e#0120xcfc9ae3d#0120x318feec8#0120xb747cc30#0120xac6a0206#0120x1148ad34#0120x8c473f2d
2018-03-11T07:13:55.755334+00:00 i6-00-24-ea-03-9f-f7 swupdate: IDLE Waiting for requests...
```
lgtm!

2022-08-18 12:32 UTC, iris-ersc approved these changes

2022-08-18 12:32 UTC, merged