Feature/phsc/rdphoen 1273 pvsn encrypt
iris-GmbH/meta-iris-base pull request #141
Opened 2022-08-11 11:20 UTC by irisPHSC

requires provisioning flash script to be executed first
https://bitbucket.iris-sensing.net/projects/GEN6/repos/meta-iris/pull-requests/304/overview

2022-08-15 14:42 UTC, irisPHSC commented
CI build
https://gitlab.devops.defra01.iris-sensing.net/MIRROR/iris-kas/-/pipelines/1581

2022-08-16 11:40 UTC, linkjumper requested changes

2022-08-16 11:40 UTC, linkjumper commented on recipes-core/initrdscripts/files/initramfs-init.sh
> +
```
dd if=rootfs.ext4.hashdevice of=/dev/mapper/irma6lvm-rootfs_a_hash
dd if=rootfs.ext4.hashdevice of=/dev/mapper/irma6lvm-rootfs_b_hash
```
is missing, right?

2022-08-16 11:40 UTC, linkjumper commented on recipes-core/initrdscripts/files/initramfs-init.sh
> +
Please sync after using dd

2022-08-16 11:40 UTC, linkjumper commented on recipes-core/initrdscripts/files/initramfs-init.sh
> +    mkdir -p /mnt/iris/counter
`mkdir -p /mnt/iris/counter` Only a good idea, if user-data is mounted to /mnt/iris . Otherwise /mnt/iris/counter get's lost on startup, because /mnt/iris is part of the initramfs. At least, adding a check should be done, or?

```
if ! grep -qs /mnt/iris /proc/mounts; then
  echo "/mnt/iris is not mounted :("
fi
```

2022-08-16 11:40 UTC, linkjumper commented on recipes-core/initrdscripts/files/initramfs-init.sh
> +    lvremove --force --yes --verbose "/dev/mapper/irma6lvm-pvsn_userdata"
The volume is removed, is the data actually gone with it? I remember the emmc_wipe script :D

2022-08-16 11:40 UTC, linkjumper commented on recipes-core/initrdscripts/files/initramfs-init.sh
> +    caam-keygen create volumeKey ccm -s 32
What's the behaviour if one runs the pvsn twice? Does it work at all? Having an error message pointing out: "Hey, there is already an caam blob", ld be nice :) Overwriting caam blobs and volumes maybe better.

2022-08-16 11:51 UTC, irisPHSC commented on recipes-core/initrdscripts/files/initramfs-init.sh
> +    mkdir -p /mnt/iris/counter
> `mkdir -p /mnt/iris/counter` Only a good idea, if user-data is mounted to /mnt/iris . Otherwise /mnt/iris/counter get's lost on startup, because /mnt/iris is part of the initramfs. At least, adding a check should be done, or?
> 
> ```
> if ! grep -qs /mnt/iris /proc/mounts; then
>   echo "/mnt/iris is not mounted :("
> fi
> ```

Should be `mkdir -p /mnt/userdata/counter`, gonna fix it.

2022-08-16 11:55 UTC, irisPHSC commented on recipes-core/initrdscripts/files/initramfs-init.sh
> +    caam-keygen create volumeKey ccm -s 32
> What's the behaviour if one runs the pvsn twice? Does it work at all? Having an error message pointing out: "Hey, there is already an caam blob", ld be nice :) Overwriting caam blobs and volumes maybe better.

The pvsn should only run once. As soon as the pvsn volumes are removed this code will not execute anymore. If you want to execute it again you have to wipe and flash again. If something went wrong before the pvsn could finish and remove the volumes than the board is a broken state which means it needs to be wiped/flashed again.

2022-08-16 12:06 UTC, irisPHSC commented on recipes-core/initrdscripts/files/initramfs-init.sh
> +    lvremove --force --yes --verbose "/dev/mapper/irma6lvm-pvsn_userdata"
> The volume is removed, is the data actually gone with it? I remember the emmc_wipe script :D

There is no easy way to secure-erase logical volumes.

2022-08-16 13:02 UTC, linkjumper commented on recipes-core/initrdscripts/files/initramfs-init.sh
> +    caam-keygen create volumeKey ccm -s 32
Adding a check, ld be nice.

2022-08-16 13:03 UTC, linkjumper commented on recipes-core/initrdscripts/files/initramfs-init.sh
> +    lvremove --force --yes --verbose "/dev/mapper/irma6lvm-pvsn_userdata"
What is the current preferred solution? Otherwise we're undermining Sec, aren't we?

2022-08-17 08:38 UTC, irisPHSC commented on recipes-core/initrdscripts/files/initramfs-init.sh
> +    lvremove --force --yes --verbose "/dev/mapper/irma6lvm-pvsn_userdata"
Implemented secure erase for logical volumes

2022-08-17 11:21 UTC, linkjumper approved these changes
Reviewed + teseted!

2022-08-17 14:13 UTC, Eximmius approved these changes
Tested & approved!

2022-08-17 14:25 UTC, iris-ersc commented
## Maintainer-Checkliste
- Ist ein Changelogeintrag vorhanden? *ja*
- Entsprechen die Commitmessages den Vorgaben? *ja*
- Wurde ein Jenkinslauf durchgeführt und war dieser fehlerfrei? *ja*
- Ist ein manueller Rebase notwendig? *nein*

Ergebnis: **Pullrequest mergefähig**
 
Muss das Kollegium nach dem Merge über die Änderungen informiert werden? **nein**

2022-08-17 14:25 UTC, merged