Feature/phsc/rdphoen 1270 disable nfs
iris-GmbH/meta-iris-base pull request #143
Opened 2022-08-16 08:35 UTC by irisPHSC

Enable NFS boot on interface unit
u-boot=> i2c dev 3
u-boot=> i2c mw 51 1F 1 1

1. Test sensor unit with security lock - Will **NOT** NFS boot
2. Test sensor unit without security lock - Will NFS boot

2022-08-16 08:45 UTC, irisPHSC commented
CI build
https://gitlab.devops.defra01.iris-sensing.net/MIRROR/iris-kas/-/pipelines/1603

2022-08-16 13:23 UTC, linkjumper requested changes

2022-08-16 13:23 UTC, linkjumper commented on recipes-bsp/u-boot/u-boot-imx/imx8mp-irma6r2/0028-imx8mp-irma6r2-Add-check-for-when-the-device-is-lock.patch
> ++	fuse_sense(1, 3, &fuse_word);
Should the return value of fuse_sense possibly be checked? Strictly speaking, fuse_word should be valid. If fuse_sense failed fuse_word is still equal 0 and nfs can still be booted.

2022-08-16 13:23 UTC, linkjumper commented on recipes-bsp/u-boot/u-boot-imx/imx8mp-irma6r2/0028-imx8mp-irma6r2-Add-check-for-when-the-device-is-lock.patch
> +
You should add your sign-off-by

2022-08-17 07:38 UTC, irisPHSC commented on recipes-bsp/u-boot/u-boot-imx/imx8mp-irma6r2/0028-imx8mp-irma6r2-Add-check-for-when-the-device-is-lock.patch
> ++	fuse_sense(1, 3, &fuse_word);
done

2022-08-17 07:38 UTC, irisPHSC commented on recipes-bsp/u-boot/u-boot-imx/imx8mp-irma6r2/0028-imx8mp-irma6r2-Add-check-for-when-the-device-is-lock.patch
> +
done

2022-08-17 11:06 UTC, irisPHSC commented
CI build with fuse_sense check
https://gitlab.devops.defra01.iris-sensing.net/MIRROR/iris-kas/-/pipelines/1709

2022-08-17 12:49 UTC, linkjumper approved these changes
LGTM!
```
[ NOT TESTED ] Test sensor unit with security lock - Will NOT NFS boot
[     OK     ] Test sensor unit without security lock - Will NFS boot
```

2022-08-17 13:31 UTC, iris-ersc requested changes
The provided patch is not used during compilation!

2022-08-17 13:49 UTC, irisPHSC commented
CI build with patch actually being applied
https://gitlab.devops.defra01.iris-sensing.net/MIRROR/iris-kas/-/pipelines/1714

2022-08-18 09:41 UTC, Eximmius approved these changes
Reviewed and approved. NFS flag is ignored on closed devices:
```
Interface Configuration Block:
        version: 0x02
        macaddr: 00:24:ea:03:b1:e2
        devicenr: 9900000107ffffff
        flags: 0x01
                nfs: 1
                dhcp: 0
flash target is MMC:2
Net:   
Warning: ethernet@30bf0000 MAC addresses don't match:
Address in ROM is          00:24:ea:03:c8:24
Address in environment is  00:24:ea:03:b1:e2
eth1: ethernet@30bf0000 [PRIME]
Fastboot: Normal
Normal Boot
Hit any key to stop autoboot:  0 
23657052 bytes read in 144 ms (156.7 MiB/s)

Authenticate image from DDR location 0x48000000...

Secure boot enabled

HAB Configuration: 0xcc, HAB State: 0x99
No HAB Events Found!

## Loading kernel from FIT Image at 48000000 ...
   Using 'conf@imx8mp-irma6r2' configuration
   Verifying Hash Integrity ... OK
```

2022-08-18 09:44 UTC, iris-ersc commented
## Maintainer-Checkliste
- Ist ein Changelogeintrag vorhanden? *ja*
- Entsprechen die Commitmessages den Vorgaben? *ja*
- Wurde ein Jenkinslauf durchgeführt und war dieser fehlerfrei? *ja*
- Ist ein manueller Rebase notwendig? *nein*

Ergebnis: **Pullrequest mergefähig**
 
Muss das Kollegium nach dem Merge über die Änderungen informiert werden? **nein**

2022-08-18 09:44 UTC, merged