[RDPHOEN-1289] set persistent path for dropbear rsa host key (IRMA 6 Release 2)
iris-GmbH/meta-iris-base pull request #146
Opened 2022-08-23 10:12 UTC by ThomasWNoack

2022-08-23 11:32 UTC, RicoBiedermann approved these changes

2022-08-23 11:37 UTC, Jasper-Ben approved these changes

2022-08-24 07:16 UTC, linkjumper requested changes

2022-08-24 07:16 UTC, linkjumper commented on recipes-core/base-files/base-files/mx8mp/fstab
> +/mnt/iris/dropbear   /var/lib/dropbear    none       defaults,bind         0  0
`/mnt/iris/dropbear` does not exist. Nevertheless, creating the folder /mnt/iris/dropbear manually has had no success. It seems that dropbear can not start and create the host key in binded mounted folder.

2022-08-29 08:46 UTC, closed without merging