Feature/ersc/rdphoen 1314 disable serializer pwm
iris-GmbH/meta-iris-base pull request #156
Opened 2022-08-26 10:20 UTC by iris-ersc

Disable PWM clock for serializer

Depends on: https://bitbucket.iris-sensing.net/projects/COMP/repos/hal_imager/pull-requests/109/overview

2022-08-26 10:35 UTC, iris-ersc commented
Pipeline: https://gitlab.devops.defra01.iris-sensing.net/MIRROR/iris-kas/-/pipelines/1960

2022-08-29 08:47 UTC, jan-hannig approved these changes

2022-08-29 11:33 UTC, linkjumper approved these changes
Tested!

2022-08-29 12:08 UTC, Eximmius requested changes

2022-08-29 12:08 UTC, Eximmius commented on recipes-kernel/linux/linux-fslc-iris/0038-RDPHOEN-1314-Disable-PWM-clock-for-serializer.patch
> ++	pll_prediv = 1; // don't divide anything ... very hacky!!
DIV_ROUND_DOWN_ULL maybe?

2022-08-29 12:10 UTC, Eximmius commented on recipes-kernel/linux/linux-fslc-iris/0038-RDPHOEN-1314-Disable-PWM-clock-for-serializer.patch
> ++	pll_prediv = 1; // don't divide anything ... very hacky!!
Not available for our current linux, maybe a custom div_round_down?

2022-08-30 07:02 UTC, ThomasWNoack requested changes
Please rebase manually

2022-08-30 07:53 UTC, Eximmius approved these changes

2022-08-30 08:28 UTC, ThomasWNoack approved these changes

2022-08-30 08:28 UTC, ThomasWNoack commented
## Maintainer Checklist
- Is there a changelog entry? *Yes*
- Do the commit messages comply with the specifications? *Yes*
- Was a Jenkins run performed and was it error-free? *Yes*
- Is a manual rebase necessary? *no*

2022-08-30 08:29 UTC, merged