Feature/ersc/rdphoen 897 add swupdate service
iris-GmbH/meta-iris-base pull request #45
Opened 2022-01-12 14:26 UTC by iris-ersc

Include swupdate in rootfs of imx8mp

Change execution of firmwarezip class. It is now based on UPDATE_PROCEDURE variable.

Needs: https://github.com/iris-GmbH/iris-kas/pull/82

2022-01-12 14:49 UTC, DanielBaumgart reviewed
Some question open, regarding QEMU-Images and zipping those firmwares.

If im'm correct they now get zipped, even if this isn't needed as use-case.

2022-01-12 14:49 UTC, DanielBaumgart commented on conf/multiconfig/qemuarm64-r1.conf
> -# skip firmware zip step, as this is a local development image
Why are these deleted?
QEMU-Images shouldn't be zipped anyway. But now they might get zipped, or am i'm wrong?

2022-01-12 14:49 UTC, DanielBaumgart commented on conf/multiconfig/qemuarm64-r2.conf
> -# skip firmware zip step, as this is a local development image
Why are these deleted?
QEMU-Images shouldn't be zipped anyway. But now they might get zipped, or am i'm wrong?

2022-01-12 14:49 UTC, DanielBaumgart commented on conf/multiconfig/qemux86-64-r1.conf
> -# skip firmware zip step, as this is a local development image
Why are these deleted?
QEMU-Images shouldn't be zipped anyway. But now they might get zipped, or am i'm wrong?

2022-01-12 14:49 UTC, DanielBaumgart commented on conf/multiconfig/qemux86-64-r2.conf
> -# skip firmware zip step, as this is a local development image
Why are these deleted?
QEMU-Images shouldn't be zipped anyway. But now they might get zipped, or am i'm wrong?

2022-01-12 14:49 UTC, DanielBaumgart commented on recipes-support/swupdate/swupdate_%.bbappend
> +	# all machines are v1.0 for now
This needs to change if we change Hardware, right? Replace Storage-Chips and such stuff?

2022-01-13 01:28 UTC, Jasper-Ben requested changes

2022-01-13 01:28 UTC, Jasper-Ben commented on classes/irma6-firmware-zip.bbclass
>      if d.getVar('SKIP_FIRMWARE_ZIP', True) == "1":
when introducing the "UPDATE_PROCEDURE" variable (which is a good idea IMO), why not delete the "SKIP_FIRMWARE_ZIP" logic?

2022-01-13 01:28 UTC, Jasper-Ben commented on conf/multiconfig/qemuarm64-r1.conf
> -# skip firmware zip step, as this is a local development image
this is not needed anymore after introducing the `UPDATE_PROCEDURE` variable in `classes/irma6-firmware-zip.bbclass`. Now images are only zipped, if their config contains the string "firmwarezip" within `UPDATE_PROCEDURE`

2022-01-13 02:04 UTC, Jasper-Ben commented
This currently breaks:

```
[AWS CodeBuild Plugin] ERROR: mc:qemux86-64-r1:irma6-test-2.0.2-dev-r0 do_createfirmwarezip: Error executing a python function in exec_func_python() autogenerated:

[AWS CodeBuild Plugin] 

[AWS CodeBuild Plugin] The stack trace of python calls that resulted in this exception/failure was:

[AWS CodeBuild Plugin] File: 'exec_func_python() autogenerated', lineno: 2, function: <module>

[AWS CodeBuild Plugin]      0001:

[AWS CodeBuild Plugin]  *** 0002:do_createfirmwarezip(d)

[AWS CodeBuild Plugin]      0003:

[AWS CodeBuild Plugin] File: '/codebuild/output/src851991482/src/meta-iris-base/classes/irma6-firmware-zip.bbclass', lineno: 32, function: do_createfirmwarezip

[AWS CodeBuild Plugin]      0028:    import yaml

[AWS CodeBuild Plugin]      0029:    import errno

[AWS CodeBuild Plugin]      0030:    import tempfile

[AWS CodeBuild Plugin]      0031:

[AWS CodeBuild Plugin]  *** 0032:    if "firmwarezip" not in d.getVar('UPDATE_PROCEDURE', ''):

[AWS CodeBuild Plugin]      0033:        return

[AWS CodeBuild Plugin]      0034:

[AWS CodeBuild Plugin]      0035:    if d.getVar('SKIP_FIRMWARE_ZIP', True) == "1":

[AWS CodeBuild Plugin]      0036:        return

[AWS CodeBuild Plugin] Exception: TypeError: argument of type 'NoneType' is not iterable

[AWS CodeBuild Plugin] 
```

see Jenkins run https://jenkins.devops.iris-sensing.net/blue/organizations/jenkins/iris-kas/detail/PR-82/2/pipeline/154

2022-01-13 08:43 UTC, iris-ersc commented on recipes-support/swupdate/swupdate_%.bbappend
> +	# all machines are v1.0 for now
Exactly. Maybe it is better to write this file elsewhere, during the initial operation in production e.g.

But right now, it is at least a reminder, that this file is necessary later on.

2022-01-14 12:23 UTC, iris-ersc commented
Image building for qemu, sc573 and imx8mp are now tested

2022-01-14 12:25 UTC, iris-ersc commented on classes/irma6-firmware-zip.bbclass
>      if d.getVar('SKIP_FIRMWARE_ZIP', True) == "1":
I have another branch that moves the firmwarezip logic in its own recipe.
For this PR I wanted to touch as little as possible in this bbclass.

2022-01-14 15:22 UTC, Jasper-Ben approved these changes
Jenkins builds now. LGTM

2022-01-17 10:07 UTC, merged