Add swupdate image creation recipe
iris-GmbH/meta-iris-base pull request #51
Opened 2022-01-26 12:37 UTC by iris-ersc

- inherits swupdate image
- sw-description and shell script based on previous work on VIDA
- check if update procedure matches
- shell script needs sfdisk and jq to operate on GPT partitions

Depends on (draft until both are merged):
- https://github.com/iris-GmbH/meta-iris-base/pull/47
- https://github.com/iris-GmbH/meta-iris-base/pull/48

Create an swuimage by running `bitbake mc:imx8mp-evk:irma6-base-swuimage`. It will build the kernel and the irma6-base image. Test the swuimage by flashing it via a netbooted firmware or on hardware that has been initialized via uuu.

2022-01-27 10:51 UTC, Jasper-Ben requested changes
please validate the sh script with shellcheck and change according to suggestions :)

2022-01-27 11:52 UTC, iris-ersc commented
> please validate the sh script with shellcheck and change according to suggestions :)

Good idea. I will look into it!

2022-02-02 09:11 UTC, Jasper-Ben approved these changes
LGTM

2022-02-02 14:00 UTC, Jasper-Ben approved these changes

2022-02-08 19:20 UTC, linkjumper commented on recipes-support/irma6-swuimage/files/update_firmware.sh
> +	sfdisk --part-attrs $EMMC_DEV "$SWU_BOOTP_OLD" ""
This toggle should happen atomically.

2022-02-08 19:50 UTC, linkjumper approved these changes

2022-02-08 22:25 UTC, Jasper-Ben commented
Rebased on current develop.

2022-02-09 09:44 UTC, iris-ersc commented on recipes-support/irma6-swuimage/files/update_firmware.sh
> +	sfdisk --part-attrs $EMMC_DEV "$SWU_BOOTP_OLD" ""
Added a TODO comment

2022-02-09 09:45 UTC, iris-ersc commented
Squashed all fixup commits

2022-02-09 13:03 UTC, merged