Feature/ersc/rdphoen 1036 imx8mp r2
iris-GmbH/meta-iris-base pull request #60
Opened 2022-03-30 09:37 UTC by iris-ersc

Working branch for irma6r2 hardware:

- Builds all "mc:imx8mp-irma6r2:irma6-*" images.

Missing (fix before merge):

- [x] Add comments to linux-fslc patches
- [x] Split u-boot patches into common and board specific patches
- [x] Adapt machine and multiconfig to hardware capabilities

Missing (for later PRs):
- Fix irma6-uuu recipes to work with irma6-r2 machine
- Move to Kernel 5.10
- Reduce RAM size to 512MB (even for 1GB hardware)

Dependencies:
- https://github.com/iris-GmbH/iris-kas/pull/91

2022-03-30 10:29 UTC, Jasper-Ben commented
@iris-ersc is this ready for review? Still in draft mode.

2022-03-30 11:06 UTC, iris-ersc commented
> @iris-ersc is this ready for review? Still in draft mode.

It's ready for review. But keep in mind, the changes noted above still need to be pushed.

2022-03-30 18:39 UTC, Jasper-Ben commented on recipes-bsp/u-boot/u-boot-imx/imx8mp-irma6r2/0002-Add-defconfig-file-for-irma6r2.patch
> +--- /dev/null
I would save newly created files (aka not changes to existing files from upstream) as "raw" files, not as patch file. Makes things easier to modify and the file easier to find (I was "desperately" searching for it after finding a reference to it within another file).

2022-03-31 13:10 UTC, iris-ersc commented on recipes-kernel/linux/linux-fslc-iris/0001-epc660-Add-device-driver-support.patch
> + arch/arm64/boot/dts/freescale/imx8mp-evk.dts |  38 +-
I would place the changes to `imx8mp-evk.dts` into a different patch file.

2022-03-31 13:36 UTC, Eximmius commented on recipes-kernel/linux/linux-fslc-iris/0001-epc660-Add-device-driver-support.patch
> + arch/arm64/boot/dts/freescale/imx8mp-evk.dts |  38 +-
I did this way with our 5.10 branch and it really looks better. Fixup for patches 0001 & 0002 will come.

2022-04-01 12:34 UTC, Eximmius commented
The irma6-uuu files for the imx8mp-evk are not being built with the linux patches. Will we support this also on the future?

2022-04-01 14:34 UTC, Jasper-Ben commented
> The irma6-uuu files for the imx8mp-evk are not being built with the linux patches. Will we support this also on the future?

I believe we should, if we plan to support the evaluation kit in the long term future. That's generally a question we need to answer (also from an automation perspective): Is there need for the evk longterm?

2022-04-01 14:37 UTC, Jasper-Ben commented on conf/machine/imx8mp-irma6r2.conf
> +UBOOT_CONFIG ??= "sd"
Do we have documentation on what these options do or should we add a brief comment here?

2022-04-01 14:38 UTC, Jasper-Ben commented on conf/machine/imx8mp-irma6r2.conf
> +IMXBOOT_TARGETS = "flash_ddr4_evk"
I believe the "_evk" is wrong here?

2022-04-01 14:39 UTC, Jasper-Ben commented on conf/machine/imx8mp-irma6r2.conf
> +#@TYPE: Machine
Please add a SPDX license header

2022-04-01 14:51 UTC, Jasper-Ben commented on conf/multiconfig/imx8mp-irma6r2.conf
> +# whitelist mongoose for this config, as the evaluation kit is only used during prototyping: https://www.cesanta.com/license/
comment here needs adjusting. It is NOT a evaluation kit anymore. Also: we need to confirm that we can continue to use mongoose in Release v2 with our existing license. I am unsure if we are subscribed to a product license or a product family license. And if we only have a product license, the terms might still apply for HWrel2:

> Product License
> This license type covers one product which may be delivered in various models


> Product Family License
> This license type covers a group of products with similar functionality, identical purposes and similar target market 

-- https://www.cesanta.com/license 


Check with legal.

2022-04-01 15:00 UTC, Jasper-Ben commented on recipes-bsp/u-boot/u-boot-imx/imx8mp-irma6r2/0004-Set-model-and-license.patch
> +-// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
What's up with the License change here? I mean yes, it should be perfectly possible for us to omit the MIT dual-license here (aka re-licensing) but is there a specific reason for this?

2022-04-01 15:03 UTC, Jasper-Ben commented on recipes-bsp/u-boot/u-boot-imx/imx8mp-irma6r2/0005-ddr4-update-training-timing-files-for-1600MHz-and-53.patch
> ++ * Copyright 2019 NXP
Add iris copyright statement

2022-04-01 15:08 UTC, Jasper-Ben commented on recipes-bsp/u-boot/u-boot-imx/imx8mp-irma6r2/0013-Use-partition-labels-in-environment-and-auto-detect-.patch
> ++	/* TODO:
please link a JIRA task here

2022-04-01 15:13 UTC, Jasper-Ben commented on recipes-bsp/u-boot/u-boot-imx_iris.inc
> +SRCBRANCH_imx8mp-irma6r2 = "imx_v2020.04_5.4.70_2.3.0"
Would it be possible to use upstream u-boot versioning here? E.g. including a NXP uboot recipe and adding our patches on top? Otherwise we need to update and maintain ourselves.

2022-04-01 15:15 UTC, Jasper-Ben commented on recipes-kernel/linux/linux-fslc-iris/0005-i2c-imx-remove-unneeded-sleep.patch
> +a delay on the startup of the i2c imx controller is not required or defined in the specs.
nice catch! :+1: maybe upstreamable?

2022-04-01 15:16 UTC, Jasper-Ben commented on recipes-kernel/linux/linux-fslc-iris/0006-Bugfix-Save-csis-format-to-internal-structure-of-imx.patch
> +Subject: [PATCH 06/29] Bugfix: Save csis format to internal structure of
Also upstreamable?

2022-04-01 15:19 UTC, Jasper-Ben commented on recipes-kernel/linux/linux-fslc-iris/0010-mipi-csi2-sam-fix-MEDIA-MIX-gasket0-dumps.patch
> +Signed-off-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>
Please add a iris sign-off so we know who to contact about this internally :slightly_smiling_face:

2022-04-01 15:19 UTC, Jasper-Ben commented on recipes-kernel/linux/linux-fslc-iris/0011-imx8-media-dev-fix-source-sink-pad-setup.patch
> +Signed-off-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>
iris sign-off

2022-04-01 15:20 UTC, Jasper-Ben commented on recipes-kernel/linux/linux-fslc-iris/0012-Hack-imx8-media-dev-Disable-unregistering-of-mxc_isi.patch
> +Bad approach! TODO: Distinguish probe failure <> deferred probing
Add JIRA tasknumber or fix before merge

2022-04-01 15:29 UTC, Jasper-Ben commented on recipes-kernel/linux/linux-fslc-iris/0028-imx8mp-irma6r2.dts-change-board-model-name.patch
> +-// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
We need to keep the GPL-2.0+ license

2022-04-01 15:29 UTC, Jasper-Ben commented on recipes-kernel/linux/linux-fslc-iris/0028-imx8mp-irma6r2.dts-change-board-model-name.patch
> +- * Copyright 2019 NXP
Keep the NXP Copyright statement

2022-04-01 15:30 UTC, Jasper-Ben commented on recipes-kernel/linux/linux-fslc-iris/0029-imx8mp-irma6r2.dts-WIP-Disable-eqos-and-fec-ethernet.patch
> +Subject: [PATCH 29/29] imx8mp-irma6r2.dts: WIP: Disable eqos and fec ethernet
Remove WIP patch

2022-04-01 15:31 UTC, Eximmius commented on recipes-kernel/linux/linux-fslc-iris/0005-i2c-imx-remove-unneeded-sleep.patch
> +a delay on the startup of the i2c imx controller is not required or defined in the specs.
We tried to send patches, but the maintainer was afraid to remove completely the sleep and I am still thinking about a mechanism on how someone could opt in to this sleep. See link on line 12 ;)

2022-04-01 15:31 UTC, Jasper-Ben commented on recipes-kernel/linux/linux-fslc-iris/0029-imx8mp-irma6r2.dts-WIP-Disable-eqos-and-fec-ethernet.patch
> ++/*
If production ready delete the appropriate lines, don't comment them (that's what a SCM system is for :wink:)

2022-04-01 15:32 UTC, Jasper-Ben requested changes
resolve my comments.

2022-04-01 15:33 UTC, Jasper-Ben commented
We might also want to add a sign-off to each patch file. There are still some without.

2022-04-01 15:38 UTC, Eximmius commented on recipes-kernel/linux/linux-fslc-iris/0006-Bugfix-Save-csis-format-to-internal-structure-of-imx.patch
> +Subject: [PATCH 06/29] Bugfix: Save csis format to internal structure of
Good question. This is not patched upstream, but I do not have a strong answer if someone asks what this exactly fixes.

2022-04-01 15:56 UTC, Eximmius commented on recipes-kernel/linux/linux-fslc-iris/0029-imx8mp-irma6r2.dts-WIP-Disable-eqos-and-fec-ethernet.patch
> +Subject: [PATCH 29/29] imx8mp-irma6r2.dts: WIP: Disable eqos and fec ethernet
We actually need this patch because of some clock pin missing on the eth phy, so this enables the board to boot without eth. This will be fixed on the redesign, so this patch will be reverted/removed when we have new boards to test.

2022-04-01 15:59 UTC, Eximmius commented on recipes-kernel/linux/linux-fslc-iris/0029-imx8mp-irma6r2.dts-WIP-Disable-eqos-and-fec-ethernet.patch
> ++/*
unfortunately, not production ready, see comment above

2022-04-01 19:53 UTC, Jasper-Ben commented on recipes-kernel/linux/linux-fslc-iris/0012-Hack-imx8-media-dev-Disable-unregistering-of-mxc_isi.patch
> +Bad approach! TODO: Distinguish probe failure <> deferred probing
Add it to the TODO comment :)

2022-04-04 07:17 UTC, linkjumper commented on recipes-bsp/u-boot/u-boot-imx/imx8mp-irma6r2/0005-ddr4-update-training-timing-files-for-1600MHz-and-53.patch
> ++ * Copyright 2019 NXP
The file is automatically generated from the NXP mscale tool and is not touched by us. I see no reason why we should add a copyright notice here. That would just be wrong.

2022-04-04 07:25 UTC, linkjumper commented on recipes-bsp/u-boot/u-boot-imx/imx8mp-irma6r2/0004-Set-model-and-license.patch
> +-// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
The file is virtually newly created by us (copied and modified). I have no qualms. What bothers you? Do you wish that we would leave it at dual license? I don't have a strong opinion against it.

2022-04-04 09:22 UTC, iris-ersc commented on recipes-bsp/u-boot/u-boot-imx/imx8mp-irma6r2/0002-Add-defconfig-file-for-irma6r2.patch
> +--- /dev/null
u-boot-imx uses in-tree defconfigs. So it is easier to just supply the patch than to dive into the recipes and change the build procedure.

2022-04-04 09:28 UTC, Eximmius commented
> > The irma6-uuu files for the imx8mp-evk are not being built with the linux patches. Will we support this also on the future?
> 
> I believe we should, if we plan to support the evaluation kit in the long term future. That's generally a question we need to answer (also from an automation perspective): Is there need for the evk longterm?
I had a strange bug where the uuu files and the wic Image were not build correctly. After a rm -rf build/tmp the problem was fixed :smiley:

2022-04-04 09:33 UTC, Jasper-Ben commented on recipes-bsp/u-boot/u-boot-imx/imx8mp-irma6r2/0002-Add-defconfig-file-for-irma6r2.patch
> +--- /dev/null
Fair. carry on :+1:

2022-04-04 09:33 UTC, iris-ersc commented on conf/machine/imx8mp-irma6r2.conf
> +UBOOT_CONFIG ??= "sd"
https://www.yoctoproject.org/docs/current/ref-manual/ref-manual.html#var-UBOOT_CONFIG

It is just a wrapper to supply different uboot defconfigs for different use cases. "sd" is just a label that gets resolved in the next line. Mostly taken from the evk config in meta-freescale.

2022-04-04 09:35 UTC, Jasper-Ben commented on recipes-bsp/u-boot/u-boot-imx/imx8mp-irma6r2/0004-Set-model-and-license.patch
> +-// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
Yeah... let's just leave it as is, before we have to do extra license checks :+1:

2022-04-04 09:35 UTC, Jasper-Ben commented on recipes-bsp/u-boot/u-boot-imx/imx8mp-irma6r2/0005-ddr4-update-training-timing-files-for-1600MHz-and-53.patch
> ++ * Copyright 2019 NXP
ah ok :+1:

2022-04-04 09:38 UTC, iris-ersc commented on conf/machine/imx8mp-irma6r2.conf
> +IMXBOOT_TARGETS = "flash_ddr4_evk"
Yes and no.

This variable sets the make target of imx-boot / imx-mkimage. "flash_ddr4_evk" does exactly the same as "flash_ddr4_val", it just expects different file names.
We could switch to "_val" and change the filenames (needs more testing), but the outcome would be the same.

2022-04-04 09:42 UTC, Jasper-Ben commented on recipes-kernel/linux/linux-fslc-iris/0029-imx8mp-irma6r2.dts-WIP-Disable-eqos-and-fec-ethernet.patch
> +Subject: [PATCH 29/29] imx8mp-irma6r2.dts: WIP: Disable eqos and fec ethernet
That's fine, but I would still remove the "WIP" from the commit message

2022-04-04 09:43 UTC, Jasper-Ben commented on recipes-kernel/linux/linux-fslc-iris/0029-imx8mp-irma6r2.dts-WIP-Disable-eqos-and-fec-ethernet.patch
> ++/*
Yes, but I still would just remove the lines instead of using comments. It makes changes easier to track and reversing is still easy due to scm.

2022-04-04 10:17 UTC, Jasper-Ben commented on conf/machine/imx8mp-irma6r2.conf
> +IMXBOOT_TARGETS = "flash_ddr4_evk"
ah ok, then leave it I'd say. but please add this as a comment to the code. :slightly_smiling_face:

2022-04-05 07:52 UTC, Jasper-Ben commented on conf/multiconfig/imx8mp-irma6r2.conf
> +# whitelist mongoose for this config, as the evaluation kit is only used during prototyping: https://www.cesanta.com/license/
legal says we are good to go. Please update this comment accordingly :slightly_smiling_face:

2022-04-05 08:35 UTC, iris-ersc commented
Squashed and rebased on develop.

2022-04-06 08:54 UTC, Eximmius approved these changes

2022-04-06 08:55 UTC, Jasper-Ben approved these changes

2022-04-06 09:59 UTC, merged