add watchdog
iris-GmbH/meta-iris-base pull request #87
Opened 2022-05-27 08:50 UTC by sven-foerster

2022-05-27 09:16 UTC, linkjumper requested changes

2022-05-27 09:16 UTC, linkjumper commented on recipes-core/busybox/busybox/busybox_watchdog.sh
> +watchdog -t 10 -T 20 /dev/watchdog
I think the default values ​​30s(reset)/60s(reboot) are ok. No arguments (-t, -T) would need to be given for this.

2022-05-27 09:16 UTC, linkjumper commented on recipes-core/busybox/busybox_%.bbappend
> +do_install_append() {
The watchdog feature must not be added for IRMA6 Release 1.

2022-05-27 09:16 UTC, linkjumper commented on recipes-core/busybox/busybox_%.bbappend
> +    #reset uboot's bootcount on successfull bootup
If I think about it any longer. The `reset_bootcount.sh` should be moved to swupdate (irma6-swuimage) in an other Pull Request. Please don't add reset_bootcount.sh here.

2022-05-27 09:42 UTC, iris-ersc requested changes

2022-06-09 14:15 UTC, Jasper-Ben commented on recipes-core/busybox/busybox_%.bbappend
> +do_install_append() {
I would negate that:
` if [ ${IRMA6_RELEASE} -ne 1 ]`

2022-06-09 14:43 UTC, sven-foerster commented on recipes-core/busybox/busybox_%.bbappend
> +SRC_URI += "${@'file://enable_watchdog.cfg' if d.getVar('IRMA6_RELEASE') == '2' else ''}"
Inhalt Deiner E-Mail:
+                ${sysconfdir}/rcS.d/S59reset_bootcount \

+rcsd="${D}${sysconfdir}/rcS.d"

steht im Widerspruch zu unten:
+                 ${sysconfdir}/rc5.d/S01watchdog \

+ rc5d="${D}${sysconfdir}/rc5.d"

rcS <-> rc5?

Wie kommt das?

2022-06-10 07:27 UTC, linkjumper reviewed
I think @Jasper-Ben is right. You should negate the logic with the queries to something like: IRMA6_RELEASE != 1,  because we want this and all other new features by default except for RELEASE 1.

Nevertheless, the current branch works as expected. Tested on imx8mpevk with irma6-maintenance-uuu for Release 2
**[OK]** Test: Kernel Panic -> reboot after 5s
**[OK]** Test: Nowayout -> 60s reboot after 60s
**[OK]** Test: busybox_watchdog.sh is called on startup


Unfortunately there is still something wrong. It seems to me that there are 2 different watchdog devices and triggering /dev/watchdog kills /dev/watchdog0.
```
root@imx8mpevk:~# dmesg | grep watchdog                                         
[    2.407621] imx2-wdt 30280000.watchdog: timeout 60 sec (nowayout=1)          
[   12.299953] watchdog: watchdog0: nowayout prevents watchdog being stopped!   
[   12.306954] watchdog: watchdog0: watchdog did not stop!
```

2022-06-20 14:14 UTC, linkjumper approved these changes

2022-06-20 16:16 UTC, Eximmius approved these changes
Tested on evk, killing wdt restarts the board after ~60 seconds:
```
587 root      3104 S    watchdog /dev/watchdog
root@imx8mpevk:~# kill -9 587
root@imx8mpevk:~# [  127.728730] watchdog: watchdog0: watchdog did not stop!
Mar  9 12:39:17 imx8mpevk user.crit kernel: [  127.728730] watchdog: watchdog0: watchdog did not stop!

root@imx8mpevk:~# 
U-Boot SPL 2020.04-imx_v2020.04_5.4.24_2.1.0+g4979a99482 (May 30 2020 - 06:50:01 +0000)
DDRINFO: start DRAM init
DDRINFO: DRAM rate 4000MTS
...
```

2022-06-20 19:11 UTC, Jasper-Ben approved these changes

2022-06-20 19:16 UTC, merged

2022-06-20 19:22 UTC, linkjumper commented
> I think @Jasper-Ben is right. You should negate the logic with the queries to something like: IRMA6_RELEASE != 1, because we want this and all other new features by default except for RELEASE 1.
> 
> Nevertheless, the current branch works as expected. Tested on imx8mpevk with irma6-maintenance-uuu for Release 2 **[OK]** Test: Kernel Panic -> reboot after 5s **[OK]** Test: Nowayout -> 60s reboot after 60s **[OK]** Test: busybox_watchdog.sh is called on startup
> 
> Unfortunately there is still something wrong. It seems to me that there are 2 different watchdog devices and triggering /dev/watchdog kills /dev/watchdog0.
> 
> ```
> root@imx8mpevk:~# dmesg | grep watchdog                                         
> [    2.407621] imx2-wdt 30280000.watchdog: timeout 60 sec (nowayout=1)          
> [   12.299953] watchdog: watchdog0: nowayout prevents watchdog being stopped!   
> [   12.306954] watchdog: watchdog0: watchdog did not stop!
> ```

See https://github.com/mirror/busybox/blob/1_31_stable/miscutils/watchdog.c:
The warning is generated by the linux watchdog driver because busybox's watchdog closes /dev/watchdog before each open. With a newer busybox version, the warning disappears. An upgrade is currently not mandatory. Here is the fix: https://github.com/mirror/busybox/commit/50a37459ff991cab97e7326490d0637ff1106cc8